### ISSUE TITLE
Integrate groovy language server with monaco-languageclient

### ISSUE THREAD

**Issue by sanketbajoria** [TypeFox/monaco-languageclient#125]
Hi,

First of all, Thanks for this superb repository. 

I am trying to integrate the groovy language server with monaco-languageclient.  I have made multiple changes
` monaco.languages.register({
    id: 'groovy',
    extensions: ['.groovy'],
    aliases: ['GROOVY', 'groovy'],
    mimetypes: ['application/java']
});`

`
monaco.editor.createModel(value, 'groovy', monaco.Uri.parse('inmemory:/model.groovy')
`

` server.createServerProcess('GROOVY', 'java', ["-jar", "D:\\git\\monaco-languageclient\\example\\groovy-language-server-0.5.5-all.jar"])`

But it is giving me below error.

java.nio.file.InvalidPathException: Illegal char <:> at index 8: inmemory:/model.groovy

I have also tried with file path, instead of inmemory but still no luck.

Please guide me, how could i achieve this

**Comment by rcjsuen** [comment]
@sanketbajoria Please share your code and error message from your second experiment (the `file` path and not the `inmemory` one).

**Comment by sanketbajoria** [comment]
@rcjsuen 
For file related changes
` monaco.editor.createModel(value, 'groovy', monaco.Uri.file('D:/git/monaco-languageclient/example/var/dummy.groovy')`

`MonacoServices.install(editor, {rootUri: "file:///D:/git/monaco-languageclient/example/var"});`

I got below error

`Caused by: java.lang.IllegalArgumentException: 'other' has different root
        at sun.nio.fs.WindowsPath.relativize(WindowsPath.java:392)
        at sun.nio.fs.WindowsPath.relativize(WindowsPath.java:44)
        at com.palantir.ls.util.WorkspaceUriSupplier.get(WorkspaceUriSupplier.java:48)
        at com.palantir.ls.groovy.GroovyTreeParser.lambda$null$3(GroovyTreeParser.java:112)
        at com.palantir.ls.groovy.GroovyTreeParser$$Lambda$32/733781802.accept(Unknown Source)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at com.palantir.ls.groovy.GroovyTreeParser.lambda$parseAllSymbols$4(GroovyTreeParser.java:110)
        at com.palantir.ls.groovy.GroovyTreeParser$$Lambda$31/281117284.accept(Unknown Source)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at com.palantir.ls.groovy.GroovyTreeParser.parseAllSymbols(GroovyTreeParser.java:109)
        at com.palantir.ls.DefaultCompilerWrapper.compile(DefaultCompilerWrapper.java:93)
        at com.palantir.ls.services.AbstractTextDocumentService.didOpen(AbstractTextDocumentService.java:74)`

**Comment by rcjsuen** [comment]
@sanketbajoria Perhaps you can try using the deprecated `rootPath` URI instead.

It's too bad that the [palantir/language-servers](https://github.com/palantir/language-servers/) repository is now archived so I'm not sure how much assistance you're going to be able to get here.

**Comment by sanketbajoria** [comment]
@rcjsuen 
I have tried that too.. but no luck

**Comment by cxwSuperman** [comment]
hello,How to install groovy-language-server with npm, I keep showing errors here.I am also doing this demand
