### ISSUE TITLE
browser example install error.

### ISSUE THREAD

**Issue by wufeng87** [TypeFox/monaco-languageclient#129]
```
aaa-mac:browser aaa$ pwd
/Users/hjm/Documents/code/github/monaco-languageclient/examples/browser
aaa-mac:browser aaa$ cnpm install
✖ Install fail! Error: [monaco-languageclient@file:../../] resolved target /Users/hjm/Documents/code/github/monaco-languageclient error: undefined
Error: [monaco-languageclient@file:../../] resolved target /Users/hjm/Documents/code/github/monaco-languageclient error: undefined
    at module.exports (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/download/local.js:30:11)
    at module.exports.throw (<anonymous>)
    at onRejected (/usr/local/lib/node_modules/cnpm/node_modules/co/index.js:81:24)
    at <anonymous>
npminstall version: 3.1.1
npminstall args: /usr/local/bin/node /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --china --userconfig=/Users/hjm/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=http://registry.npm.taobao.org
```

**Comment by mariomurrent-softwaresolutions** [comment]
Same for me - npm install in browser does not work as well as npm install in all folders + root

**Comment by eprst** [comment]
getting a different error in `example` and `examples/browser`:

```
monaco-languageclient/example - [master] » npm install
npm ERR! path /Users/konstantin/workspace/monaco-languageclient/example/node_modules/.staging/monaco-languageclient-cd466a88/node_modules/@types/node
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/konstantin/workspace/monaco-languageclient/example/node_modules/.staging/monaco-languageclient-cd466a88/node_modules/@types/node' -> '/Users/konstantin/workspace/monaco-languageclient/example/node_modules/.staging/@types/node-35683d36'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/konstantin/.npm/_logs/2019-01-15T02_11_01_744Z-debug.log
monaco-languageclient/example - [master] » npm --version
6.5.0
monaco-languageclient/example - [master] » node --version
v11.6.0
```

**Comment by srcherukuri** [comment]
getting the same error reported by eprst above.

**Comment by MichaelJohnCoan** [comment]
Ditto.  Same errors as eprst.

**Comment by MichaelJohnCoan** [comment]
All:
I found a resolved issue that addressed the eprst problem: https://github.com/TypeFox/monaco-languageclient/issues/118
Apparently, the examples will build if you delete the package-lock.json files first (in the appropriate folders).  This fixed the problem that I had that was expressed by eprst.  I'm not sure if it will correct wufeng87's original issue however.
