### ISSUE TITLE
monaco-languageclient claims it supports workspace/configuration when it doesn't

### ISSUE THREAD

**Issue by rcjsuen** [TypeFox/monaco-languageclient#169]
```
$ node lib/server.js --external
JSON Server: (node:8738) UnhandledPromiseRejectionWarning: Error: Unhandled method workspace/configuration
    at handleResponse (/home/remy/code/github/dockerfile-language-server-nodejs/node_modules/vscode-jsonrpc/lib/main.js:436:48)
    at processMessageQueue (/home/remy/code/github/dockerfile-language-server-nodejs/node_modules/vscode-jsonrpc/lib/main.js:263:17)
    at Immediate.setImmediate [as _onImmediate] (/home/remy/code/github/dockerfile-language-server-nodejs/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

JSON Server: (node:8738) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8738) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
We register support for `workspace/configuration` in `MonacoLanguageClient` but the default implementation of `MonacoWorkspace` doesn't support this as it doesn't provide an override for `configurations`.
https://github.com/TypeFox/monaco-languageclient/blob/10f66f4ccfa41c615733071b32e174003f55016f/client/src/monaco-language-client.ts#L88

**Comment by rcjsuen** [comment]
Actually, after some research I'm not sure if `MonacoWorkspace is to blame or not. It feels like the failure is happening way before that?

**Comment by rcjsuen** [comment]
This looks like my own fault with having put too many breakpoints in the code. There might still be an issue around `workspace/configuration` requests but I am closing this for now.
