### ISSUE TITLE
Error with getLanguageId on latest version

### ISSUE THREAD

**Issue by rw-access** [TypeFox/monaco-languageclient#303]
Hey @CGNonofr, it looks like the latest changes from #301 are breaking for me.

Relevant installed versions:
```
@codingame/monaco-jsonrpc: 0.3.1
@codingame/monaco-languageclient: 0.17.0
monaco-editor: 0.30.1
@monaco-editor/react: 4.3.1
@monaco-editor/loader: 1.2.0
```

 Here's a stack trace, appears the problem is in `onDidChangeTextDocument`
```
helpers.ts:111 Uncaught TypeError: model.getLanguageId is not a function
    at MonacoWorkspace.setModel (monaco-workspace.ts:71)
    at MonacoWorkspace.addModel (monaco-workspace.ts:48)
    at new MonacoWorkspace (monaco-workspace.ts:23)
    at create (monaco-services.ts:30)
    at Object.install (monaco-services.ts:35)
    ...
```

**Comment by rw-access** [comment]
Oh, looks like there's a 0.28 cached Monaco somewhere...
```
editor@0.28.1/min/vs/editor/editor.main.js:60:13525)
    at https://cdn.jsdelivr.net/npm/monaco-editor@0.28.1/min/vs/editor/editor.main.js:573:12639
    at Array.map (<anonymous>)
    at https://cdn.jsdelivr.net/npm/monaco-editor@0.28.1/min/vs/editor/editor.main.js:573:12628
    at Generator.next (<anonymous>)
    at https://cdn.jsdelivr.net/npm/monaco-editor@0.28.1/min/vs/editor/editor.main.js:60:13728
    at new Promise (<anonymous>)
    at ke (https://cdn.jsdelivr.net/npm/monaco-editor@0.28.1/min/vs/editor/editor.main.js:60:13525)
    at s (https://cdn.jsdelivr.net/npm/monaco-editor@0.28.1/min/vs/editor/editor.main.js:573:12526)
    at https://cdn.jsdelivr.net/npm/monaco-editor@0.28.1/min/vs/editor/editor.main.js:639:1471
    at S (https://cdn.jsdelivr.net/npm/monaco-editor@0.28.1/min/vs/editor/editor.main.js:60:14204)
    at r.runner (https://cdn.jsdelivr.net/npm/monaco-editor@0.28.1/min/vs/editor/editor.main.js:639:1445)
    at r.doRun (https://cdn.jsdelivr.net/npm/monaco-editor@0.28.1/min/vs/editor/editor.main.js:60:17977)
    at r.onTimeout (https://cdn.jsdelivr.net/npm/monaco-editor@0.28.1/min/vs/editor/editor.main.js:60:17943)
    ...
```

**Comment by rw-access** [comment]
Problem solved: my dependency `@monaco-editor/loader` was pinned to load 0.28.1
