### ISSUE TITLE
Undo not sending textDocument/didChange

### ISSUE THREAD

**Issue by ewenmaclean** [TypeFox/monaco-languageclient#332]
First off, thanks a lot for the excellent example here. I have made a branch with which to repro an error I am getting, which I am struggling to track down exactly in the code. I have prebuilt the standalone (non-websocket) xtext language server from this excellent project by @cdietrich : 

https://github.com/cdietrich/xtext-languageserver-example

and rewritten the example so that it communicates with this. This works well, but highlights an issue where the monaco-languageclient does not apparently send an update to the server of a textDocument/didChange on undo which causes problems when the xtext server then sends text positions for e.g. hover as they can cause an out of bounds error looking for the reference in the text previous to the undo (Which xtext erroneously is referring to). Here is the fork and branch with this implemented:

https://github.com/ewenmaclean/monaco-languageclient/tree/UndoMissingExample

The original project does not suffer this problem within VSCode which does send the `textDocument/didChange` on undo so it seems to be particular to this monaco languageClient.

Build is as normal. To repro the error - do the following in the editor on localhost:3000: First add the text
```
Hello Xtext!
Hello VSCode from Xtext!
Hello ThisFile from Other!
```
then paste in at the end
```


Hello you!
```
Now hover over the validation error at "you!". Now delete this section, then press ctrl-Z so it reappears and then hover over the "you!" error again and you should get this error trace in the console:
```
SEVERE: Internal error: java.lang.IndexOutOfBoundsException: Position [
  line = 8
  character = 7
] text was : Hello Xtext!
Hello VSCode from Xtext!
Hello ThisFile from Other!

java.util.concurrent.CompletionException: java.lang.IndexOutOfBoundsException: Position [
  line = 8
  character = 7
] text was : Hello Xtext!
Hello VSCode from Xtext!
Hello ThisFile from Other!

	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.eclipse.xtext.ide.server.concurrent.AbstractRequest.logAndCompleteExceptionally(AbstractRequest.java:73)
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$doRun$0(ReadRequest.java:69)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IndexOutOfBoundsException: Position [
  line = 8
  character = 7
] text was : Hello Xtext!
Hello VSCode from Xtext!
Hello ThisFile from Other!

	at org.eclipse.xtext.ide.server.Document.getOffSet(Document.java:62)
	at org.eclipse.xtext.ide.server.hover.HoverService.hover(HoverService.java:53)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$hover$32(LanguageServerImpl.java:718)
	at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:438)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.hover(LanguageServerImpl.java:717)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$hover$31(LanguageServerImpl.java:704)
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$doRun$0(ReadRequest.java:66)
	... 5 more
```

**Comment by CGNonofr** [comment]
Good catch! it seems it was broken in the very last version, a fix will come soon

**Comment by ewenmaclean** [comment]
Thanks very much!

**Comment by CGNonofr** [comment]
It should be fixed with the last published version, do you confirm?
