### ISSUE TITLE
upgrading to monaco-languageclient version 6 throws command failed error

### ISSUE THREAD

**Issue by OliverwengFiltered** [TypeFox/monaco-languageclient#491]
Hi there,

I'm currently using monaco-languageclient version v5, when I'm upgrading it to v6, it throws command failed error.

it says 
```
error /Users/xxxxx/xxxxxxx/node_modules/monaco-languageclient: Command failed.
Exit code: 127
Command: monaco-treemending
Arguments:
```

I have added the `postinstall`  prop under package.json with value `monaco-treemending` and also tried manually run `npx monaco-treemending`, it prints `Monaco-editor was tree-mended`.

however, when I run `yarn upgrade monaco-languageclient`, it prints the above command failed error.

any ideas how to solve ?

**Comment by kaisalmen** [comment]
Hi @OliverwengFiltered thank you for reporting the problem. A similar the similar or the sam problem reported here: https://github.com/CodinGame/monaco-vscode-api/issues/113

The second time it tries to apply the patch to monaco-editor it exits with error.

**Comment by OliverwengFiltered** [comment]
@kaisalmen 
yes you are correct, the second time if I try `npx monaco-treemending` it throws below error

```
Error: Unable to apply patch on /Users/xxx/xxx/xxxx/xxxx/node_modules/monaco-editor/esm/vs/base/browser/browser.js
    at Object.patched (file:///Users/oliverweng/Desktop/DevelopmentApps/Filtered/node_modules/vscode/dist/monaco-treemending.js:854:30)
    at file:///Users/oliverweng/Desktop/DevelopmentApps/Filtered/node_modules/vscode/dist/monaco-treemending.js:820:15
    at Object.loadFile (file:///Users/oliverweng/Desktop/DevelopmentApps/Filtered/node_modules/vscode/dist/monaco-treemending.js:845:21)
```

is this something you folks can fix ?

**Comment by kaisalmen** [comment]
Yes, but not immediately. You need to live with it for a couple of days or use a workaround. pnpm seems to be the most problematic. `npm ci` will always work, 😉

**Comment by kaisalmen** [comment]
@OliverwengFiltered in addition to the upcoming fix linked above I have updated the README: https://github.com/TypeFox/monaco-languageclient#using-monaco-languageclient

Any project using `monaco-languageclient` is not required to add and run the `postinstall` itself. This done by `monaco-languageclient` during dependency installation (=`npm install`). This is something I have misunderstood and one of the conclusions I draw from here: https://github.com/TypeFox/monaco-languageclient-ng-example/issues/1

**Comment by kaisalmen** [comment]
@OliverwengFiltered this is finally fixed with: https://www.npmjs.com/package/monaco-languageclient/v/6.0.3

**Comment by kaisalmen** [comment]
@CGNonofr any idea just by looking at the errors? My first guess is mismatching tsconfig/webpack config with regard to module/moduleResolution , but it is just guesswork without seeing the config.

**Comment by CGNonofr** [comment]
My guess is the patch wasn't applied

**Comment by kaisalmen** [comment]
@OliverwengFiltered to my knowledge there is nothing as simple as `npm ci` with yarn, so please delete the node_modules folder again once, eventually remove the lock file and do a full re-installation.

**Comment by OliverwengFiltered** [comment]
@kaisalmen 

cleaning node)modules, remove lock files didn't seem to help. Still hitting same kinda error.

it seems some export became unavailable, are we certain that the v6.0.3 compatible with monaco-editor 0.37.1 ? and vscode api 1.78.8 ?

Thanks.

![Screenshot 2023-06-05 at 4 41 03 PM](https://github.com/TypeFox/monaco-languageclient/assets/28814939/24686b1c-024b-4ec9-a6ea-f2062e50dada)

**Comment by kaisalmen** [comment]
@OliverwengFiltered this is really weird. I now added `yarn` and `pnpm` verification packages into the repo, see https://github.com/TypeFox/monaco-languageclient#pure-bundler-verification

It is not part of the npm workspace and allows to check install and manual invocation of treemending.

**Comment by kaisalmen** [comment]
I push another update. It is working for both package managers including multiple manual executions of `yarn run test:treemending` or `pnpm run test:treemending` after install.

**Comment by kaisalmen** [comment]
@OliverwengFiltered 
You can give https://www.npmjs.com/package/monaco-languageclient/v/6.1.0-next.1 a try. It depends on `monaco-vscode-api` `1.79.1` and `monaco-editor` `0.38.0`, see [PR #501](https://github.com/TypeFox/monaco-languageclient/pull/501)

**Comment by OliverwengFiltered** [comment]
Hi @kaisalmen 

the v6.1.0-next.1 is promising, I am able to build it with some minor code changes on my end. I'm logging my changes here in case it helps you folks for additional improvements or for anyone else to see if needed.

* after upgrading to v6.1.0-next.1 with yarn, it initially complains about mp3 files, and wasm files missing loader, so I added the corresponding loader in my webpack config.
* after fixing the loader problem above, it starts complaining about two packages still missing. they are: `vscode-textmate vscode-oniguruma`, so I manually added by executing `yarn add vscode-textmate vscode-oniguruma -D`
* did one more build, and now I can see it successfully built.
* when I tried the actual page that has the editor with latest built resources, it starts to complain the `MonacoServices` obj under LanguageClientLib is undefined, and then I did some research and realized that I should probably switch to `initServices`, instead of calling `MonacoServices.get();` and `MonacoServices.install()`
* after the above all procedures, I am able to initialize the editor, and initialize the language server connection. however, I still see some error in my console when it tries to connect to my Java and C# language server. (C, C++, Python etc seems to be running perfectly.) although those errors are printing in my console, all the language server functions are all performing expectedly though. 

appreciate any sight, regarding to those error messages.

Thanks!

![Screenshot 2023-06-06 at 3 34 15 PM](https://github.com/TypeFox/monaco-languageclient/assets/28814939/aca796c9-9ae5-4a40-bdd1-b1c8c5868d8c)

**Comment by kaisalmen** [comment]
@OliverwengFiltered did you configure services with `initServices` or did you leave it empty? I know it may not be possible, but sharing a repo or reproducible example makes problem cracking a lot easier.

@CGNonofr `monaco-languageclient` always initializes the files service even if nothing is configured. Is this not sufficient in this case. Any idea from just looking at the error?

**Comment by CGNonofr** [comment]
This error comes from the FileService not being overriden, what make you think it's not sufficient?

**Comment by kaisalmen** [comment]
> what make you think it's not sufficient?

Doesn't the files service initialize an in memory file system that is used if nothing else is done?

**Comment by CGNonofr** [comment]
Correct!

**Comment by OliverwengFiltered** [comment]
@kaisalmen 
to answer your previous question, yes, I am using `initServices()` without passing any params, assuming it will inherit the default configs.
 
where to see additional debug log ? i have enabled it with `await initServices({ debugLogging: true });`, but the error log seems to be the same.

![Screenshot 2023-06-07 at 1 09 22 PM](https://github.com/TypeFox/monaco-languageclient/assets/28814939/d84840fa-50be-439a-8707-57b8717624d5)

**Comment by kaisalmen** [comment]
@OliverwengFiltered you should at least see these info message, because the files service is always initialized:
![image](https://github.com/TypeFox/monaco-languageclient/assets/21079138/6d087e24-24e3-4fa2-b8e5-89865847dfbd)

**Comment by kaisalmen** [comment]
@OliverwengFiltered that's good news

> BTW, do you folks have insights about why there is a need to install vscode-textmate vscode-oniguruma two packages manually ?

Don't know. When using `npm` there is no need for that.

**Comment by OliverwengFiltered** [comment]
@kaisalmen 

all good, thank you for the support and knowledge sharing.

I will be looking forward to the next release !

have a great weekend!
