### ISSUE TITLE
Uncaught Error: Extension api not initialized when create the client

### ISSUE THREAD

**Issue by minh-nguyen-kms** [TypeFox/monaco-languageclient#495]
Hi there,
I got the error when trying to connect the client with Python JSON-RPC language server
```
Uncaught Error: Extension api not initialized
    at To (extHost.js:375:15)
    at get onDidOpenTextDocument [as onDidOpenTextDocument] (workspace.js:48:42)
    at new n (textSynchronization.js:14:42)
    at n.value (monaco-language-client.ts:85:30)
    at new e (client.js:255:14)
    at n.<anonymous> (createSuper.js:12:24)
    at new n (monaco-language-client.ts:53:9)
```

Installed packages
```
    "@codingame/monaco-vscode-api": "^1.78.6",
    "monaco-editor": "^0.37.1",
    "monaco-editor-workers": "^0.37.0",
    "monaco-languageclient": "^6.0.1",
```

and the LanguageClient creator function look like
```
export function createLanguageClient(
  transports: MessageTransports
): MonacoLanguageClient {
  return new MonacoLanguageClient({
    name: 'Sample Language Client',
    clientOptions: {
      // use a language id as a document selector
      documentSelector: ['python'],
      // disable the default error handler
      errorHandler: {
        error: () => ({ action: ErrorAction.Continue }),
        closed: () => ({ action: CloseAction.DoNotRestart }),
      },
    },
    // create a language client connection from the JSON RPC connection on demand
    connectionProvider: {
      get: () => {
        return Promise.resolve(transports);
      },
    },
  });
}
```

**Comment by minh-nguyen-kms** [comment]
The issue is solved. I forgot to call initalService before creating the editor
```
await initServices()
```
