### ISSUE TITLE
Monaco invalid actions configuration

### ISSUE THREAD

**Issue by BusinessDuck** [TypeFox/monaco-languageclient#527]
Hi everyone! Lets take a look at new problem with editor actions and localization webpack module

```typescript
// monaco playground

activeTextEditorControl.getSupportedActions().filter(item => !item.label) // returns [] empty array
// Mean each monaco action have `label` property.

// language-client + monaco

activeTextEditorControl.getSupportedActions().filter(item => !item.label) 

// returns 6 sctions without label (incorrect)

'editor.action.inspectTMScopes', 'editor.action.dirtydiff.previous', 'editor.action.dirtydiff.next', 'workbench.action.editor.previousChange', 'workbench.action.editor.nextChange', 'editor.action.toggleWordWrap'
```

Is it pure vscode actions, texmate and workbench, why are available? (textmate service is disabled)

**Comment by BusinessDuck** [comment]
These errors is produced by incorrect actions setup during runtime working:

Comand Pelette call:
```
iconLabels.js:36 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'indexOf')
    at stripIcons (iconLabels.js:36:14)
```


Context menu call:
```
TypeError: Cannot read properties of undefined (reading 'value')
    at createMenuHide (menuService.js:385:85)
```

**Comment by BusinessDuck** [comment]
I guess here is the reason: we're using https://github.com/wang12124468/monaco-editor-esm-webpack-plugin and https://github.com/wang12124468/monaco-editor-nls for localization.

**Comment by BusinessDuck** [comment]
The problem was solved by changes in nls module:

```javascript
// More callns for nls.js in webpack loader
if (/monaco-vscode-api[\\\/]dist[\\\/]vscode[\\\/]vs.+\.js$/.test(this.resourcePath)) {
 vsPath = this.resourcePath.split(/monaco-vscode-api[\\\/]dist[\\\/]vscode/).pop();
}
```

And webpack config

```js
	new NormalModuleWebpackReplacementPlugin(
		/\/(vs\-)?nls\.js/,
		function(resource) {
			resource.request = nls;
			resource.resource = nls;
		}
	),
```

```js
	{
				include: /(monaco-editor(-core)?[\\\/]esm)|(monaco-vscode-api[\\\/]dist)/,
				exclude: /[\\\/]worker/,
				use: [
					{
						loader: putYouLoaderHere
					},
				],
			},
```
