### ISSUE TITLE
Cannot find module 'vary'

### ISSUE THREAD

**Issue by liudonghua123** [TypeFox/monaco-languageclient#559]
I tried to run python example via `npm run dev` and `npm run start:example:server:python`. But when I execute `npm run start:example:server:python`, I got the following errors.

I tried with the latest node 18.x and 20.x, it's the same problems.

```
 Liu.D.H    monaco-languageclient   main ≡   18.14.2   6ms⠀   npm run start:example:server:python
npm WARN cli npm v10.2.0 does not support Node.js v18.14.2. This version of npm supports the following node versions: `^18.17.0 || >=20.5.0`. You can find the latest version at https://nodejs.org/.

> start:example:server:python
> npm run start:server:python --workspace packages/examples

npm WARN cli npm v10.2.0 does not support Node.js v18.14.2. This version of npm supports the following node versions: `^18.17.0 || >=20.5.0`. You can find the latest version at https://nodejs.org/.

> monaco-languageclient-examples@6.6.1 start:server:python
> node --loader ts-node/esm src/python/server/direct.ts

(node:23496) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Error: Cannot find module 'vary'
Require stack:
- D:\code\node\monaco-languageclient\node_modules\express\lib\response.js
- D:\code\node\monaco-languageclient\node_modules\express\lib\express.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (D:\code\node\monaco-languageclient\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\code\node\monaco-languageclient\node_modules\express\lib\response.js:36:12)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .js] (D:\code\node\monaco-languageclient\node_modules\ts-node\src\index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1117:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\code\\node\\monaco-languageclient\\node_modules\\express\\lib\\response.js',
    'D:\\code\\node\\monaco-languageclient\\node_modules\\express\\lib\\express.js'
  ]
}
npm ERR! Lifecycle script `start:server:python` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: monaco-languageclient-examples@6.6.1
npm ERR!   at location: D:\code\node\monaco-languageclient\packages\examples

 Liu.D.H    monaco-languageclient   main ≡   18.14.2   12.799s⠀  

 Liu.D.H    monaco-languageclient   main ≡   18.14.2   0ms⠀   node -v                 cmd  14:55:29 
v18.14.2

 Liu.D.H    monaco-languageclient   main ≡   18.14.2   42ms⠀   nvm use 20.8.0         cmd  14:55:31 
Now using node v20.8.0 (64-bit)

 Liu.D.H    monaco-languageclient   main ≡   20.8.0   12.499s⠀   npm run start:example:server:python

> start:example:server:python
> npm run start:server:python --workspace packages/examples


> monaco-languageclient-examples@6.6.1 start:server:python
> node --loader ts-node/esm src/python/server/direct.ts

(node:25820) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/modules/cjs/loader:1048
  const err = new Error(message);
              ^

Error: Cannot find module 'vary'
Require stack:
- D:\code\node\monaco-languageclient\node_modules\express\lib\response.js
- D:\code\node\monaco-languageclient\node_modules\express\lib\express.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (D:\code\node\monaco-languageclient\node_modules\express\lib\response.js:36:12)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\code\\node\\monaco-languageclient\\node_modules\\express\\lib\\response.js',
    'D:\\code\\node\\monaco-languageclient\\node_modules\\express\\lib\\express.js'
  ]
}

Node.js v20.8.0
npm ERR! Lifecycle script `start:server:python` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: monaco-languageclient-examples@6.6.1
npm ERR!   at location: D:\code\node\monaco-languageclient\packages\examples

 Liu.D.H    monaco-languageclient   main ≡   20.8.0   10.894s⠀  
```

**Comment by liudonghua123** [comment]
I tried to install `vary` package. It didn't work either.

```
 Liu.D.H    monaco-languageclient   main ≡   20.8.0   10.894s⠀   npm i vary           cmd  14:56:05 
(node:13276) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)

up to date, audited 522 packages in 36s

115 packages are looking for funding
  run `npm fund` for details

1 moderate severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

 Liu.D.H    monaco-languageclient   main ≡  ~2   20.8.0   38.081s⠀   npm run start:example:server:python

> start:example:server:python
> npm run start:server:python --workspace packages/examples


> monaco-languageclient-examples@6.6.1 start:server:python
> node --loader ts-node/esm src/python/server/direct.ts

(node:3852) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/modules/cjs/loader:1048
  const err = new Error(message);
              ^

Error: Cannot find module 'vary'
Require stack:
- D:\code\node\monaco-languageclient\node_modules\express\lib\response.js
- D:\code\node\monaco-languageclient\node_modules\express\lib\express.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (D:\code\node\monaco-languageclient\node_modules\express\lib\response.js:36:12)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\code\\node\\monaco-languageclient\\node_modules\\express\\lib\\response.js',
    'D:\\code\\node\\monaco-languageclient\\node_modules\\express\\lib\\express.js'
  ]
}

Node.js v20.8.0
npm ERR! Lifecycle script `start:server:python` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: monaco-languageclient-examples@6.6.1
npm ERR!   at location: D:\code\node\monaco-languageclient\packages\examples

 Liu.D.H    monaco-languageclient   main ≡  ~2   20.8.0   6.559s⠀   
```

**Comment by liudonghua123** [comment]
Yes, I performed a clean and fresh installation beforehand.

And I also noticed that it seemed missing some files in `node_modules`, So I removed it and executed `npm i` again. Now it worked as expected.

Thanks! @kaisalmen
