### ISSUE TITLE
Yeoman project starter and npm run build:web fail during build/execution

### ISSUE THREAD

**Issue by CarlosGamez-Nova** [TypeFox/monaco-languageclient#601]
# Problem Description

When starting a new project from scratch as per the [Get Started](https://langium.org/docs/getting-started/) instructions the `yo langium` command throws an error during the final build step.

# How to reproduce

- Create a new project from scratch using the `yo langium` tool
- Accept all the default options: Include VSCode extension, Include CLI, Include Web worker
- Also running the `npm run build:web` command on the project causes the same failure

![image](https://github.com/TypeFox/monaco-languageclient/assets/118949383/ab1429a6-99a2-46be-8c39-8ff809a31d46)

# Expected behaviour

Fresh project is created and all build actions work correctly

# Observed behaviour

The project is created successfully but during the last stages of the process, the `build:web` command causes the error shown below. The same behaviour is observed if the `npm run build:web` command is run at a later time.

```terminal
"initialize" is not exported by "node_modules/vscode/extensions.js", imported by "node_modules/monaco-languageclient/lib/monaco-vscode-api-services.js".
file: D:/Programming/experiments/hello-world/node_modules/monaco-languageclient/lib/monaco-vscode-api-services.js:6:9
4:  * ------------------------------------------------------------------------------------------ */
5: import { ILogService, initialize, StandaloneServices } from 'vscode/services';
6: import { initialize as initializeVscodeExtensions } from 'vscode/extensions';
            ^
7: import getLanguagesServiceOverride from '@codingame/monaco-vscode-languages-service-override';
8: import getModelServiceOverride from '@codingame/monaco-vscode-model-service-override';
error during build:
RollupError: "initialize" is not exported by "node_modules/vscode/extensions.js", imported by "node_modules/monaco-languageclient/lib/monaco-vscode-api-services.js".
    at error (file:///D:/Programming/experiments/hello-world/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at Module.error (file:///D:/Programming/experiments/hello-world/node_modules/rollup/dist/es/shared/node-entry.js:13745:16)
    at Module.traceVariable (file:///D:/Programming/experiments/hello-world/node_modules/rollup/dist/es/shared/node-entry.js:14175:29)
    at ModuleScope.findVariable (file:///D:/Programming/experiments/hello-world/node_modules/rollup/dist/es/shared/node-entry.js:12615:39)
    at ReturnValueScope.findVariable (file:///D:/Programming/experiments/hello-world/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at ChildScope.findVariable (file:///D:/Programming/experiments/hello-world/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at Identifier.bind (file:///D:/Programming/experiments/hello-world/node_modules/rollup/dist/es/shared/node-entry.js:8319:40)
    at CallExpression.bind (file:///D:/Programming/experiments/hello-world/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
    at CallExpression.bind (file:///D:/Programming/experiments/hello-world/node_modules/rollup/dist/es/shared/node-entry.js:9890:15)
    at AwaitExpression.bind (file:///D:/Programming/experiments/hello-world/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
✖ An error occured while running langium:app#install
Error langium

Command failed with exit code 1: npm run build:web
```

**Comment by msujew** [comment]
We already have an issue for this over at the Langium repo, see https://github.com/eclipse-langium/langium/issues/1315.

**Comment by CarlosGamez-Nova** [comment]
My apologies. I didn't see the open issue. Closing this now.
