### ISSUE TITLE
about docker-compose Error volta only support x86_64 OS

### ISSUE THREAD

**Issue by claybyl** [TypeFox/monaco-languageclient#724]
Dear great author, I encountered some issues while using docker-compose to build eclipsejdtls.

I am using a Mac M2 chip, but volta only supports the x86_64 architecture.
 I replaced the volta install node20 script with:
**RUN apt install -y curl \ 
&& curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
 apt-get install -y nodejs **

I successfully built and started the container, but _npm i_  seems did not run successfully in the container. I can provide specific error information, and I would be very grateful if you have time to help me identify the problem

**Comment by kaisalmen** [comment]
I will push an update

**Comment by claybyl** [comment]
> I will push an update

extremely grateful for your  replay.  i had tried install the eclipse language server in my pc; but there is anthor error confused me:

//here is the error detail. 
`
{"jsonrpc":"2.0","id":0,"method":"initialize","params":{"processId":null,"clientInfo":{"name":"Code - OSS","version":"1.91.1"},"locale":"en","rootPath":"/Users/baoyuelong1/Downloads/byl/jdt-language-server-1.38.0-202408011337/workspace","rootUri":"file:///Users/baoyuelong1/Downloads/byl/jdt-language-server-1.38.0-202408011337/workspace","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional","normalizesLineEndings":true,"changeAnnotationSupport":{"groupsOnLabel":true}},"configuration":true,"didChangeWatchedFiles":{"dynamicRegistration":true,"relativePatternSupport":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"tagSupport":{"valueSet":[1]},"resolveSupport":{"properties":["location.range"]}},"codeLens":{"refreshSupport":true},"executeCommand":{"dynamicRegistration":true},"didChangeConfiguration":{"dynamicRegistration":true},"foldingRange":{"refreshSupport":true},"semanticTokens":{"refreshSupport":true},"fileOperations":{"dynamicRegistration":true,"didCreate":true,"didRename":true,"didDelete":true,"willCreate":true,"willRename":true,"willDelete":true},"inlineValue":{"refreshSupport":true},"inlayHint":{"refreshSupport":true},"diagnostics":{"refreshSupport":true}},"textDocument":{"publishDiagnostics":{"relatedInformation":true,"versionSupport":false,"tagSupport":{"valueSet":[1,2]},"codeDescriptionSupport":true,"dataSupport":true},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true,"tagSupport":{"valueSet":[1]},"insertReplaceSupport":true,"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"insertTextModeSupport":{"valueSet":[1,2]},"labelDetailsSupport":true},"insertTextMode":2,"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]},"completionList":{"itemDefaults":["commitCharacters","editRange","insertTextFormat","insertTextMode","data"]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true},"activeParameterSupport":true},"contextSupport":true},"definition":{"dynamicRegistration":true,"linkSupport":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true,"tagSupport":{"valueSet":[1]},"labelSupport":true},"codeAction":{"dynamicRegistration":true,"isPreferredSupport":true,"disabledSupport":true,"dataSupport":true,"resolveSupport":{"properties":["edit"]},"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"honorsChangeAnnotations":true},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true,"rangesSupport":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true,"prepareSupportDefaultBehavior":1,"honorsChangeAnnotations":true},"documentLink":{"dynamicRegistration":true,"tooltipSupport":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true,"foldingRangeKind":{"valueSet":["comment","imports","region"]},"foldingRange":{"collapsedText":false}},"declaration":{"dynamicRegistration":true,"linkSupport":true},"selectionRange":{"dynamicRegistration":true},"callHierarchy":{"dynamicRegistration":true},"semanticTokens":{"dynamicRegistration":true,"tokenTypes":["namespace","type","class","enum","interface","struct","typeParameter","parameter","variable","property","enumMember","event","function","method","macro","keyword","modifier","comment","string","number","regexp","operator","decorator"],"tokenModifiers":["declaration","definition","readonly","static","deprecated","abstract","async","modification","documentation","defaultLibrary"],"formats":["relative"],"requests":{"range":true,"full":{"delta":true}},"multilineTokenSupport":false,"overlappingTokenSupport":false,"serverCancelSupport":true,"augmentsSyntaxTokens":true},"linkedEditingRange":{"dynamicRegistration":true},"typeHierarchy":{"dynamicRegistration":true},"inlineValue":{"dynamicRegistration":true},"inlayHint":{"dynamicRegistration":true,"resolveSupport":{"properties":["tooltip","textEdits","label.tooltip","label.location","label.command"]}},"diagnostic":{"dynamicRegistration":true,"relatedDocumentSupport":false}},"window":{"showMessage":{"messageActionItem":{"additionalPropertiesSupport":true}},"showDocument":{"support":true},"workDoneProgress":true},"general":{"staleRequestSupport":{"cancel":true,"retryOnContentModified":["textDocument/semanticTokens/full","textDocument/semanticTokens/range","textDocument/semanticTokens/full/delta"]},"regularExpressions":{"engine":"ECMAScript","version":"ES2020"},"markdown":{"parser":"marked","version":"1.1.0"},"positionEncodings":["utf-16"]},"notebookDocument":{"synchronization":{"dynamicRegistration":true,"executionSummarySupport":true}}},"trace":"off","workspaceFolders":[{"uri":"file:///Users/baoyuelong1/Downloads/byl/jdt-language-server-1.38.0-202408011337/workspace","name":"workspace"}]}}
Eclipse JDT LS Server received:
{
  jsonrpc: '2.0',
  id: 0,
  method: 'initialize',
  params: {
    processId: null,
    clientInfo: { name: 'Code - OSS', version: '1.91.1' },
    locale: 'en',
    rootPath: '/Users/baoyuelong1/Downloads/byl/jdt-language-server-1.38.0-202408011337/workspace',
    rootUri: 'file:///Users/baoyuelong1/Downloads/byl/jdt-language-server-1.38.0-202408011337/workspace',
    capabilities: {
      workspace: [Object],
      textDocument: [Object],
      window: [Object],
      general: [Object],
      notebookDocument: [Object]
    },
    trace: 'off',
    workspaceFolders: [ [Object] ]
  }
}
Eclipse JDT LS Server: WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign

Eclipse JDT LS Server: 8月 09, 2024 5:05:13 下午 org.apache.aries.spifly.BaseActivator log
信息: Registered provider ch.qos.logback.classic.servlet.LogbackServletContainerInitializer of service jakarta.servlet.ServletContainerInitializer in bundle ch.qos.logback.clasc

Eclipse JDT LS Server: 8月 09, 2024 5:05:13 下午 org.apache.aries.spifly.BaseActivator log
信息: Registered provider ch.qos.logback.classic.spi.LogbackServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle ch.qos.logback.classic

Eclipse JDT LS Server: 8月 09, 2024 5:05:14 下午 org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireError
严重: Missing header Content-Length in input "HTTP/1.1 400 Bad Request
Connection: close

"
java.lang.IllegalStateException: Missing header Content-Length in input "HTTP/1.1 400 Bad Request
Connection: close

"
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:91)
        at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)


Eclipse JDT LS Server: 8月 09, 2024 5:05:14 下午 org.eclipse.lsp4j.jsonrpc.RemoteEndpoint notify
警告: Failed to send notification message.
org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.net.SocketException: Broken pipe
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:72)
        at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$1(ParentProcessWatcher.java:144)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.notify(RemoteEndpoint.java:135)
        at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:88)
        at jdk.proxy3/jdk.proxy3.$Proxy10.logMessage(Unknown Source)
        at org.eclipse.jdt.ls.core.internal.JavaClientConnection.logMessage(JavaClientConnection.java:104)
        at org.eclipse.jdt.ls.core.internal.handlers.LogHandler.processLogMessage(LogHandler.java:168)
        at org.eclipse.jdt.ls.core.internal.handlers.LogHandler$1.logging(LogHandler.java:93)
        at org.eclipse.core.internal.runtime.RuntimeLog.logToListeners(RuntimeLog.java:163)
        at org.eclipse.core.internal.runtime.PlatformLogWriter.logged(PlatformLogWriter.java:109)
        at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory.safeLogged(ExtendedLogReaderServiceFactory.java:108)
        at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory.logPrivileged(ExtendedLogReaderServiceFactory.java:259)
        at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory.log(ExtendedLogReaderServiceFactory.java:229)
        at org.eclipse.osgi.internal.log.ExtendedLogServiceFactory.log(ExtendedLogServiceFactory.java:106)
        at org.eclipse.osgi.internal.log.LoggerImpl.log(LoggerImpl.java:91)
        at org.eclipse.osgi.internal.log.LoggerImpl.log(LoggerImpl.java:82)
        at org.eclipse.osgi.internal.log.LoggerImpl.log(LoggerImpl.java:77)
        at org.eclipse.core.internal.runtime.Log.log(Log.java:82)
        at org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin.log(JavaLanguageServerPlugin.java:393)
        at org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin.logInfo(JavaLanguageServerPlugin.java:409)
        at org.eclipse.jdt.ls.core.internal.LanguageServerApplication.start(LanguageServerApplication.java:62)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1454)
Caused by: java.net.SocketException: Broken pipe
        at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:425)
        at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:445)
        at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:831)
        at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1035)
        at java.base/java.io.OutputStream.write(OutputStream.java:127)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:67)
        ... 33 more


Eclipse JDT LS Server: 8月 09, 2024 5:05:14 下午 org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireStreamClosed
信息: Connection reset
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:328)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:961)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:79)
        at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)

`

**Comment by kaisalmen** [comment]
⬆️ that's why we use the container. Local installation usually make problems. Please use the container. Does the new setting solve your issue?

**Comment by claybyl** [comment]
> ⬆️ that's why we use the container. Local installation usually make problems. Please use the container. Does the new setting solve your issue?

Thank u @kaisalmen ,i totally agree.  When i use platform: linux/amd64 setting, the base-image (eclipse-temurin:17-jdk) cannot be pulled.  I m trying to fix the problem.  Really appreciate your help

**Comment by kaisalmen** [comment]
> the base-image (eclipse-temurin:17-jdk) cannot be pulled

I have an idea... it is likely required that the architecture needs to be specified there as well

**Comment by kaisalmen** [comment]
Just pushed another update that should fix amd64 usage for now (arm64 is prepared, but commented).
Hint: You need to use containerd in Docker Desktop for multi-platform builds.

**Comment by kaisalmen** [comment]
@claybyl volta V2 was released in the meantime. Can you try if it works when you un-comment this [line](https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/resources/eclipse.jdt.ls/docker-compose.yml#L10)

**Comment by kaisalmen** [comment]
I will integrate an arm based build with GitHub Actions to see if the problem can be resolved.

**Comment by kaisalmen** [comment]
Only x86_64 is supported right now and we won't change that right.
