### ISSUE TITLE
Unable to find a file.

### ISSUE THREAD

**Issue by vivekburman** [TypeFox/monaco-languageclient#727]
I'm getting file not found error, when trying to launch this file. I checked for case-sensitive but that does not seems to be the case.
1. The app codebase is in different path whereas I'm trying to access a completely different path for the golang code.

Actual path: "C:\Users\vivek\go_test\postgres_db_sql_source\something.go"
Uri:
`
{
    "$mid": 1,
    "path": "/c:/users/vivek/go_test/postgres_db_sql_source/something.go",
    "scheme": "file"
}
`

Error message:
file not found
EntryNotFound (FileSystemError): file not found
    at FileSystemProviderError.create (http://localhost:3000/static/js/bundle.js:552165:27)
    at createFileSystemProviderError (http://localhost:3000/static/js/bundle.js:552175:34)
    at RegisteredFileSystemProvider._lookup (http://localhost:3000/static/js/bundle.js:332136:124)
    at RegisteredFileSystemProvider._lookupAsDirectory (http://localhost:3000/static/js/bundle.js:332146:24)
    at RegisteredFileSystemProvider.mkdirSync (http://localhost:3000/static/js/bundle.js:332282:25)
    at RegisteredFileSystemProvider.registerFile (http://localhost:3000/static/js/bundle.js:332172:35)
    at InitializeMonaco (http://localhost:3000/static/js/bundle.js:3716:22)
    at func (http://localhost:3000/static/js/src_pages_SQLConnectorPage_tsx-data_font_woff2_charset_utf-8_base64_d09GMgABAAAAABFoAAsAAAAAJ-b0f7bf.chunk.js:679:66)
    at http://localhost:3000/static/js/src_pages_SQLConnectorPage_tsx-data_font_woff2_charset_utf-8_base64_d09GMgABAAAAABFoAAsAAAAAJ-b0f7bf.chunk.js:682:5
    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:270734:30)

**Comment by kaisalmen** [comment]
Hi @vivekburman without further context (e.g. repository with reproducible example) we are unable to help you.

**Comment by vivekburman** [comment]
I got that part fixed was due to workspace path and file uri path. I thought both were supposed to be absolute.
But I've this new issue because of React.StrictMode I guess. Creating a new ticket and closing this.
