### ISSUE TITLE
Cannot build/dev main

### ISSUE THREAD

**Issue by rubenfiszel** [TypeFox/monaco-languageclient#733]
Hi,

I'm following the quick start instructions but here are the errors:

```
▶ npm run dev  

> dev
> vite


  VITE v5.4.2  ready in 151 ms

  ➜  Local:   http://localhost:20001/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
Error:   Failed to scan for dependencies from entries:
  /git/monaco-languageclient/index.html
/git/monaco-languageclient/packages/examples/bare.html
/git/monaco-languageclient/packages/examples/wrapper_ws.html
/git/monaco-languageclient/packages/examples/browser.html
/git/monaco-languageclient/packages/examples/wrapper_statemachine.html
/git/monaco-languageclient/packages/examples/wrapper_langium.html
/git/monaco-languageclient/packages/examples/python.html
/git/monaco-languageclient/packages/examples/groovy.html
/git/monaco-languageclient/packages/examples/react_statemachine.html
/git/monaco-languageclient/packages/examples/react_python.html
/git/monaco-languageclient/packages/examples/wrapper_ts.html
/git/monaco-languageclient/packages/examples/wrapper_adv.html

  ✘ [ERROR] Failed to resolve entry for package "@typefox/monaco-editor-react". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]

    node_modules/vite/node_modules/esbuild/lib/main.js:1225:21:
      1225 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///git/monaco-languageclient/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:46541:15)
    at resolvePackageEntry (file:///git/monaco-languageclient/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:46538:3)
    at tryNodeResolve (file:///git/monaco-languageclient/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:46354:16)
    at ResolveIdContext.resolveId (file:///git/monaco-languageclient/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:46104:19)
    at PluginContainer.resolveId (file:///git/monaco-languageclient/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:48919:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (file:///git/monaco-languageclient/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:49530:22)
    at async file:///git/monaco-languageclient/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:49692:28
    at async requestCallbacks.on-resolve (/git/monaco-languageclient/node_modules/vite/node_modules/esbuild/lib/main.js:1225:22)
    at async handleRequest (/git/monaco-languageclient/node_modules/vite/node_modules/esbuild/lib/main.js:647:11)

  This error came from the "onResolve" callback registered here:

    node_modules/vite/node_modules/esbuild/lib/main.js:1150:20:
      1150 │       let promise = setup({
           ╵                     ^

    at setup (file:///git/monaco-languageclient/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:49680:13)
    at handlePlugins (/git/monaco-languageclient/node_modules/vite/node_modules/esbuild/lib/main.js:1150:21)
    at buildOrContextImpl (/git/monaco-languageclient/node_modules/vite/node_modules/esbuild/lib/main.js:873:5)
    at Object.buildOrContext (/git/monaco-languageclient/node_modules/vite/node_modules/esbuild/lib/main.js:699:5)
    at /git/monaco-languageclient/node_modules/vite/node_modules/esbuild/lib/main.js:2032:68
    at new Promise (<anonymous>)
    at Object.context (/git/monaco-languageclient/node_modules/vite/node_modules/esbuild/lib/main.js:2032:27)
    at Object.context (/git/monaco-languageclient/node_modules/vite/node_modules/esbuild/lib/main.js:1874:58)
    at prepareEsbuildScanner (file:///git/monaco-languageclient/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:49477:24)

  The plugin "vite:dep-scan" was triggered by this import

    packages/examples/src/langium/statemachine/main-react.tsx:8:38:
      8 │ import { MonacoEditorReactComp } from '@typefox/monaco-editor-react';
        ╵                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ```
  
  This after a clean clone and npm install

**Comment by kaisalmen** [comment]
Hi  @rubenfiszel did you perform `npm run build` to build all local packages/libs first?

**Comment by rubenfiszel** [comment]
It fixed it, i'm an idiot

**Comment by kaisalmen** [comment]
It's Friday. Don't be to hard on yourself. 🙂
