### ISSUE TITLE
Getting this error: “Error: Services are already initialized”

### ISSUE THREAD

**Issue by shivam6543** [TypeFox/monaco-languageclient#743]
I’m trying to load two monaco editors in one page but getting this error:

```
lifecycle.js:84 Uncaught (in promise) Error: Services are already initialized
    at checkServicesNotInitialized (lifecycle.js:84:1)
    at initialize (services.js:185:1)
    at importAllServices (services.ts:120:1)
    at async initServices (services.ts:89:1)
    at async setupEditor (MonacoEditor.js:16:1)
```

But when I render a single editor, everything works fine.

I’m using the following packages:

```
"monaco-editor": "npm:@codingame/monaco-vscode-editor-api@~8.0.4",
"monaco-editor-wrapper": "^5.5.3",
"monaco-languageclient": "^8.8.3",
"vscode": "npm:@codingame/monaco-vscode-api@~8.0.4",
```

Simplified code:

```
import React, { useEffect, useRef } from 'react';
import * as monaco from 'monaco-editor';
import { initServices } from 'monaco-languageclient/vscode/services';
import { useWorkerFactory } from 'monaco-editor-wrapper/workerFactory';
import '@codingame/monaco-vscode-standalone-languages';

const MonacoEditor = ({ id, value, language }) => {
    const editorRef = useRef(null); // Create a ref for the editor
    useWorkerFactory({
        ignoreMapping: false,
    });
    useEffect(() => {

        const setupEditor = async () => {
            // Initialize services
            await initServices({});

            monaco.editor.create(editorRef.current, { // Use the ref here
                value,
                language,
            });
        };

        setupEditor(); // Call the async function

    }, [value, language]); // Ensure dependencies are correct

    return <div ref={editorRef} style={{ width: '800px', height: '600px', border: '1px solid grey' }}></div>; // Attach ref to the div
};

export default MonacoEditor;
```

App.js:

```

import React from 'react';
import MonacoEditor from './MonacoEditor';

const App = () => {
    return (
        <div>
            <MonacoEditor
                id="monaco-editor-root"
                value={`body {\n    background-color: red;\n}`}
                language="css"
            />
            <MonacoEditor
                id="monaco-editor-root1"
                value={`<html>\n    <head>\n        <title>Hello World</title>\n    </head>\n    <body>\n        <h1>Hello World</h1>\n    </body>\n</html>`}
                language="html"
            />
        </div>
    );
};

export default App;
```

can anyone please tell me what i am missing here?

**Comment by shivam6543** [comment]
@kaisalmen @CGNonofr any chance you could help me figure out what I might be missing?
