### ISSUE TITLE
Problem with 6.0.0-next.2

### ISSUE THREAD

**Issue by cdietrich** [TypeFox/monaco-languageclient#762]
Hi,

does this error ring a bell

```
dom.js:566 Uncaught TypeError: Cannot read properties of undefined (reading 'parentNode')
    at getShadowRoot (dom.js:566:20)
    at isInShadowDOM (dom.js:563:14)
    at StandaloneThemeService.registerEditorContainer (standaloneThemeService.js:219:13)
    at new StandaloneEditor2 (standaloneCodeEditor.js:163:51)
    at new <anonymous> (injection.js:14:13)
    at new ConfiguredStandaloneEditor (monaco.js:76:13)
    at _InstantiationService._createInstance (instantiationService.js:120:24)
    at _InstantiationService.createInstance (instantiationService.js:94:27)
    at Object.createConfiguredEditor [as create] (monaco.js:291:10)
    at EditorAppClassic.createEditors (editorAppBase.ts:120:41)
```

**Comment by kaisalmen** [comment]
@cdietrich the htmlContainer / htmlElement configuration changed. Check one of the examples

**Comment by kaisalmen** [comment]
For example:
https://github.com/TypeFox/monaco-languageclient/blob/main/packages/examples/src/python/client/config.ts

**Comment by cdietrich** [comment]
arggg now i am also getting the compile error.
ts language server is very wired
