### ISSUE TITLE
new errors in 6.0.0

### ISSUE THREAD

**Issue by cdietrich** [TypeFox/monaco-languageclient#768]
@kaisalmen is there somewhere a changelog?

```
this._commandService.onDidExecuteCommand is not a function

TypeError: this._commandService.onDidExecuteCommand is not a function
    at new InlineCompletionsController2 (inlineCompletionsController.js:134:45)
    at _InstantiationService._createInstance (instantiationService.js:120:24)
    at _InstantiationService.createInstance (instantiationService.js:94:27)
    at CodeEditorContributions._instantiateById (codeEditorContributions.js:98:57)
    at CodeEditorContributions._instantiateSome (codeEditorContributions.js:76:18)
    at codeEditorContributions.js:35:18
    at new InlineCompletionsController2 (inlineCompletionsController.js:134:45)
    at _InstantiationService._createInstance (instantiationService.js:120:24)
    at _InstantiationService.createInstance (instantiationService.js:94:27)
    at CodeEditorContributions._instantiateById (codeEditorContributions.js:98:57)
    at CodeEditorContributions._instantiateSome (codeEditorContributions.js:76:18)
    at codeEditorContributions.js:35:18
    at errors.js:10:29
```

**Comment by kaisalmen** [comment]
@cdietrich are you already using -next.4 versions?

**Comment by cdietrich** [comment]
ahhh there is also a new codingame. missed that one

**Comment by kaisalmen** [comment]
@cdietrich yes, the dependency management is tricky. We need to find a better way to signal the user during install that dependencies mismatch. The current peerDependency definition is not sufficient.
