### ISSUE TITLE
Issue hooking up a language server: Uncaught Exception:  Error: Message header must separate key and value using :

### ISSUE THREAD

**Issue by tylerl0706** [TypeFox/monaco-languageclient#86]
I'm trying to get this project working with the [PowerShell langauage server](https://github.com/powershell/powershelleditorservices) but I'm running into a strange exception when running PowerShell Editor Services as a separate process:

```
Uncaught Exception:  Error: Message header must separate key and value using :
Error: Message header must separate key and value using :
    at /home/tylerleonhardt/Desktop/monaco-test/monaco-languageclient-master/example/node_modules/vscode-jsonrpc/lib/messageReader.js:68:23
    at Array.forEach (<anonymous>)
    at MessageBuffer.tryReadHeaders (/home/tylerleonhardt/Desktop/monaco-test/monaco-languageclient-master/example/node_modules/vscode-jsonrpc/lib/messageReader.js:65:17)
    at StreamMessageReader.onData (/home/tylerleonhardt/Desktop/monaco-test/monaco-languageclient-master/example/node_modules/vscode-jsonrpc/lib/messageReader.js:194:43)
    at Socket.<anonymous> (/home/tylerleonhardt/Desktop/monaco-test/monaco-languageclient-master/example/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
```

In case it's important, we do send a few additional custom messages that the typical LSP messages - but they're still communicating the same way via stdio. Here's an example custom message written to stdio:

```
Content-Length: 261

{"jsonrpc":"2.0","method":"powerShell/executionStatusChanged","params":{"executionOptions":{"writeOutputToHost":false,"writeErrorsToHost":false,"addToHistory":false,"interruptCommandPrompt":false,"writeInputToHost":false},"executionStatus":1,"hadErrors":false}}
```

Any thoughts?

**Comment by akosyakov** [comment]
@tylerl0706 Hi, it says that JSON-RPC headers are malformed. It should not be related to additional custom messages. Have you tried to debug `messageReader.js`, particularly `tryReadHeaders` method?

**Comment by tylerl0706** [comment]
@akosyakov yep this was totally my fault... I had some logging going to stdio and that was getting picked up by monaco-languageclient... but I've since hit a different issue. I'll open in a new issue since it's totally unrelated to this.

Thanks!
